# Generated by Django 5.2.6 on 2026-09-07 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_is_listed_alter_project_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'is_active'], name='projects_pr_user_id_5f83f5_idx'),
        ),
    ]
