# Generated by Django 5.2.6 on 2026-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectmember_projects_pr_user_id_5f83f5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('NEW', 'Yangi loyiha'), ('CONTINUATION', 'Davom ettiriladigan'), ('NEEDS_CLASSIFICATION', "Turlash kerak bo'lgan"), ('MODERNIZATION', 'Modernizatsiya va takomillashtirish'), ('MAINTENANCE', "Texnik qo'llab-quvvatlash")], db_index=True, default='NEW', max_length=30, verbose_name='Loyiha turi'),
        ),
    ]
