# Generated by Django 5.2.6 on 2026-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('NEW', 'Yangi loyiha'), ('CONTINUATION', 'Davom ettiriladigan'), ('NEEDS_CLASSIFICATION', "Tuzatish kerak bo'lgan"), ('MODERNIZATION', 'Modernizatsiya va takomillashtirish'), ('MAINTENANCE', "Texnik qo'llab-quvvatlash")], db_index=True, default='NEW', max_length=30, verbose_name='Loyiha turi'),
        ),
    ]
