# Generated by Django 5.2.6 on 2026-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('NEW', 'Yangi loyiha'), ('CONTINUATION', 'Davom ettiriladigan'), ('NEEDS_CLASSIFICATION', "Tuzatish kerak bo'lgan")], db_index=True, default='NEW', max_length=30, verbose_name='Loyiha turi'),
        ),
    ]
