# Generated by Django 5.2.6 on 2026-09-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task.assigned', 'Vazifa biriktirildi'), ('task.reassigned', "Vazifa o'tkazildi"), ('task.review', 'Tekshiruvga tushdi'), ('task.decided', 'Tekshiruv natijasi'), ('task.comment', 'Yangi izoh'), ('chat.message', 'Chat xabari'), ('chat.direct', 'Shaxsiy xabar'), ('join.request', "Qo'shilish so'rovi"), ('project.deadline', 'Loyiha muddati yaqin'), ('suggestion.new', 'Yangi taklif'), ('suggestion.decided', "Taklif bo'yicha qaror"), ('inquiry.new', "Yangi so'rov"), ('inquiry.decided', "So'rov bo'yicha qaror"), ('order.new', 'Yangi buyurtma'), ('order.status', "Buyurtma holati o'zgardi"), ('order.reminder', 'Buyurtma bildirishnomasi')], db_index=True, max_length=32, verbose_name='Turi'),
        ),
    ]
