# Generated by Django 5.2.6 on 2026-09-08 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Talabnoma raqami')),
                ('system_name', models.CharField(default='TeamFlow', max_length=150, verbose_name='Tizim nomi')),
                ('module', models.CharField(blank=True, max_length=150, verbose_name='Modul')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('department', models.CharField(max_length=200, verbose_name="Buyurtma qilayotgan bo'linma")),
                ('responsible_person', models.CharField(max_length=200, verbose_name="Mas'ul shaxs")),
                ('priority', models.CharField(choices=[('URGENT', "Shoshilinch / O'ta muhim"), ('HIGH', 'Yuqori'), ('MEDIUM', "O'rta"), ('LOW', 'Past')], db_index=True, default='HIGH', max_length=20, verbose_name='Ustuvorligi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Kerakli muddat')),
                ('current_state', models.TextField(verbose_name="1.1 Joriy holat (nima ishlamayapti / nimani o'zgartirish kerak)")),
                ('requested_change', models.TextField(verbose_name="1.2 Talab qilinayotgan o'zgartirish (aniq va batafsil tavsif)")),
                ('reason', models.TextField(verbose_name='1.3 Sabab / maqsad (qonun talabi, biznes ehtiyoji, xato va h.k.)')),
                ('affected_modules', models.TextField(blank=True, verbose_name="2.1 Qaysi modul / funksionallikka ta'sir qiladi")),
                ('dependent_systems', models.TextField(blank=True, verbose_name="2.2 Bog'liq tizimlar / integratsiyalar")),
                ('change_nature', models.CharField(choices=[('USER_FACING', "Foydalanuvchiga ko'rinadigan (Frontend/UI)"), ('BACKEND', "Ichki o'zgarish (Backend / Baza / API)"), ('BOTH', "Ikkalasi ham (To'liq tizim bo'ylab)")], default='BOTH', max_length=20, verbose_name="2.3 O'zgarish xarakteri")),
                ('additional_materials', models.TextField(blank=True, verbose_name='3. Skrinshotlar, xato xabarlari, texnik talablar va h.k.')),
                ('test_result', models.TextField(blank=True, verbose_name='4.1 Test qilish natijasi')),
                ('status', models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('COMPLETED', 'Bajarildi'), ('REJECTED', 'Rad etildi')], db_index=True, default='NEW', max_length=20, verbose_name='Holati')),
                ('client_signer', models.CharField(blank=True, max_length=200, verbose_name='Buyurtmachi (F.I.Sh., sana)')),
                ('executor_signer', models.CharField(blank=True, max_length=200, verbose_name='Ijrochi tomonidan qabul qilindi (F.I.Sh., sana)')),
                ('estimated_resources', models.CharField(blank=True, max_length=200, verbose_name='Baholangan vaqt / resurslar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'zgartirish so'rovi (Buyurtma)",
                'verbose_name_plural': "O'zgartirish so'rovlari (Buyurtmalar)",
                'ordering': ['-created_at'],
            },
        ),
    ]
