# Generated by Django 5.2.6 on 2026-09-08 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('projects', '0010_projectmember_projects_pr_user_id_5f83f5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-created_at'], 'verbose_name': "O'zgartirish so'rovi (Buyurtma / TZ)", 'verbose_name_plural': "O'zgartirish so'rovlari (Buyurtmalar / TZ)"},
        ),
        migrations.AddField(
            model_name='changerequest',
            name='assigned_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul PM"),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='pm_deadline',
            field=models.DateField(blank=True, help_text='Loyiha menejeri tomonidan tasdiqlangan topshirish sanasi', null=True, verbose_name='PM belgilagan yakuniy muddat'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='pm_estimated_duration',
            field=models.CharField(blank=True, default='', help_text='PM tomonidan belgilangan bajarilish vaqti (masalan: 10 ish kuni, 3 hafta, 1 oy)', max_length=150, verbose_name='Qanchada tugashi (PM bahosi)'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='pm_notes',
            field=models.TextField(blank=True, default='', help_text='Loyiha menejeri izohi yoki topshiriq tafsilotlari', verbose_name="PM xulosasi va ko'rsatmalari"),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Ushbu TZ biriktirilgan loyiha (axborot tizimi)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='projects.project', verbose_name='Tegishli loyiha'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='tz_file',
            field=models.FileField(blank=True, help_text='Texnik topshiriq hujjati (PDF, Word, Excel, Arxiv va h.k.)', null=True, upload_to='orders/tz/', verbose_name='TZ fayli'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='tz_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TZ fayl nomi'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='tz_file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='TZ fayl hajmi (bayt)'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Kerakli muddat (Buyurtmachi so'ragan)"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='priority',
            field=models.CharField(choices=[('URGENT', "Shoshilinch / O'ta muhim"), ('HIGH', 'Yuqori'), ('MEDIUM', "O'rta"), ('LOW', 'Past')], db_index=True, default='HIGH', max_length=20, verbose_name='Ustuvorligi / Muhimlilik turi'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana'),
        ),
    ]
