# Generated by Django 5.2.6 on 2026-09-08 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_changerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Joriy versiya'),
        ),
        migrations.CreateModel(
            name='ChangeRequestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versiya raqami')),
                ('tz_file', models.FileField(blank=True, help_text='Ushbu versiyaga tegishli TZ hujjati (PDF, Word, Excel va h.k.)', null=True, upload_to='orders/tz/versions/', verbose_name='TZ fayli')),
                ('tz_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='TZ fayl nomi')),
                ('tz_file_size', models.PositiveBigIntegerField(default=0, verbose_name='TZ fayl hajmi (bayt)')),
                ('change_note', models.TextField(blank=True, default='', verbose_name="O'zgarishlar tavsifi / sababi")),
                ('status', models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('COMPLETED', 'Bajarildi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror vaqti')),
                ('decision_note', models.TextField(blank=True, default='', verbose_name='PM qaror izohi')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_order_versions', to=settings.AUTH_USER_MODEL, verbose_name='Qaror qilgan PM')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.changerequest', verbose_name='Buyurtma / TZ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_versions', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan shaxs')),
            ],
            options={
                'verbose_name': 'TZ versiyasi',
                'verbose_name_plural': 'TZ versiyalari',
                'ordering': ['-version'],
                'unique_together': {('order', 'version')},
            },
        ),
    ]
