# Generated by Django 5.2.6 on 2026-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_changerequest_version_changerequestversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='order_type',
            field=models.CharField(choices=[('NEW', 'Yangi loyiha'), ('CONTINUATION', 'Davom ettiriladigan'), ('NEEDS_CLASSIFICATION', "Turlash kerak bo'lgan"), ('MODERNIZATION', 'Modernizatsiya va takomillashtirish'), ('MAINTENANCE', "Texnik qo'llab-quvvatlash")], db_index=True, default='NEW', help_text="Loyiha turi: Yangi loyiha, Davom ettiriladigan yoki Turlash kerak bo'lgan", max_length=30, verbose_name='Loyiha / Talabnoma turi'),
        ),
    ]
