# Generated by Django 5.2.6 on 2026-09-08 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_changerequest_order_type'),
        ('tasks', '0007_task_tasks_task_project_bdde34_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, help_text='Ushbu buyurtma/topshiriq biriktirilgan dasturchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dev_orders', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul dasturchi / Ijrochi"),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text="Loyihadagi bog'langan dasturiy vazifa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='tasks.task', verbose_name='Tegishli vazifa (Task)'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('COMPLETED', 'Bajarildi'), ('REJECTED', 'Rad etildi')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='changerequestversion',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('COMPLETED', 'Bajarildi'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
