# Generated by Django 5.2.6 on 2026-09-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_changerequest_assigned_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='current_state',
            field=models.TextField(blank=True, default='', verbose_name="1.1 Joriy holat (nima ishlamayapti / nimani o'zgartirish kerak)"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='module',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='1.3 Sabab / maqsad (qonun talabi, biznes ehtiyoji, xato va h.k.)'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='requested_change',
            field=models.TextField(blank=True, default='', verbose_name="1.2 Talab qilinayotgan o'zgartirish (aniq va batafsil tavsif)"),
        ),
    ]
