# Generated by Django 5.2.6 on 2026-09-09 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_changerequest_current_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='client_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshqarma tasdiqlagan sana'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan boshqarma vakili'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_feedback_note',
            field=models.TextField(blank=True, default='', verbose_name='Boshqarma fikri / qaytarishdagi xatolik izohi'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tugatishga topshirilgan sana'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='completion_file',
            field=models.FileField(blank=True, help_text='Bajarilgan ish haqidagi hujjat yoki hisobot (PDF, Word, rasm va h.k.)', null=True, upload_to='orders/completion/', verbose_name='Tugatilgan ish hujjati'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='completion_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tugatilgan ish fayli nomi'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='completion_file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tugatilgan ish fayl hajmi'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='completion_note',
            field=models.TextField(blank=True, default='', verbose_name="Tugatilgan ish bo'yicha hisobot / PM izohi"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='changerequestversion',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
