# Generated by Django 5.2.6 on 2026-09-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_changerequest_client_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequestversion',
            name='requested_change',
            field=models.TextField(blank=True, default='', verbose_name="Talab qilinayotgan o'zgarishlar tavsifi"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='changerequestversion',
            name='status',
            field=models.CharField(choices=[('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
