# Generated by Django 5.2.6 on 2026-09-10 04:33

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_changerequestversion_requested_change_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.orders.models.order_attachment_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Fayl nomi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Fayl hajmi (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.changerequest', verbose_name='Buyurtma / TZ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma ilovasi / fayli',
                'verbose_name_plural': 'Buyurtma ilovalari / fayllari',
                'ordering': ['id'],
            },
        ),
    ]
