# Generated by Django 5.2.6 on 2026-09-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Buyurtma qilayotgan bo'linma"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Mas'ul shaxs"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='changerequestversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', 'Dasturchiga topshirildi'), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
