# Generated by Django 5.2.6 on 2026-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_changerequest_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', "Dasturchiga yo'naltirildi"), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], db_index=True, default='NEW', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='changerequestversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('NEW', 'Yangi (Yuborilgan)'), ('ACCEPTED', 'Qabul qilindi'), ('ASSIGNED_TO_DEV', "Dasturchiga yo'naltirildi"), ('IN_PROGRESS', 'Jarayonda'), ('TESTING', 'Test qilinmoqda'), ('READY_FOR_REVIEW', "Boshqarma tasdig'ida"), ('COMPLETED', 'Bajarildi (Tasdiqlangan)'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilingan (Atmen)')], default='NEW', max_length=20, verbose_name='Holati'),
        ),
    ]
