# Generated by Django 5.2.6 on 2026-09-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_changerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='client_feedback_file',
            field=models.FileField(blank=True, help_text='Boshqarma tomonidan qaytarishda ilova qilingan kamchiliklar yoki yangilangan TZ hujjati', null=True, upload_to='orders/feedback/', verbose_name='Kamchilik / Tuzatish TZ hujjati'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_feedback_file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Kamchilik fayli nomi'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='client_feedback_file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Kamchilik fayl hajmi'),
        ),
    ]
