# Generated by Django 5.2.6 on 2026-09-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_changerequest_client_feedback_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='request_no',
        ),
    ]
