# Generated by Django 5.2.6 on 2026-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_changerequest_request_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='pm_start_date',
            field=models.DateField(blank=True, help_text='Topshiriqni bajarishni boshlash sanasi', null=True, verbose_name='PM belgilagan boshlanish sanasi'),
        ),
    ]
