# Generated by Django 5.2.6 on 2026-09-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_changerequest_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='order_type',
            field=models.CharField(choices=[('NEW', 'Yangi loyiha'), ('CONTINUATION', 'Davom ettiriladigan'), ('NEEDS_CLASSIFICATION', "Tuzatish kerak bo'lgan")], db_index=True, default='NEW', help_text="Loyiha turi: Yangi loyiha, Davom ettiriladigan yoki Tuzatish kerak bo'lgan", max_length=30, verbose_name='Loyiha / Talabnoma turi'),
        ),
    ]
