# Generated by Django 5.2.6 on 2026-09-07 13:25

import apps.inquiries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name="So'rov matni")),
                ('scope', models.CharField(choices=[('OPEN', 'Ochiq'), ('CLOSED', 'Yopiq')], db_index=True, default='OPEN', max_length=10, verbose_name='Turi')),
                ('is_anonymous', models.BooleanField(default=False, help_text="Muallif hech kimga ko'rsatilmaydi", verbose_name='Anonim')),
                ('status', models.CharField(choices=[('PENDING', "Ko'rib chiqilmoqda"), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='PENDING', max_length=10, verbose_name='Holat')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Qaror vaqti')),
                ('decision_note', models.TextField(blank=True, verbose_name='Boshliq izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Qaror qilgan')),
            ],
            options={
                'verbose_name': "So'rov",
                'verbose_name_plural': "So'rovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.inquiries.models.inquiry_file_path, verbose_name='Fayl')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Hajmi (bayt)')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='inquiries.inquiry', verbose_name="So'rov")),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_files', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': "So'rov fayli",
                'verbose_name_plural': "So'rov fayllari",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('FOR', "Qo'shilaman"), ('AGAINST', "Qo'shilmayman"), ('NEUTRAL', 'Betarafman')], max_length=10, verbose_name='Tanlov')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='inquiries.inquiry', verbose_name="So'rov")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_votes', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': "So'rov ovozi",
                'verbose_name_plural': "So'rov ovozlari",
            },
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['scope', '-created_at'], name='inquiries_i_scope_b14e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['author', '-created_at'], name='inquiries_i_author__de6aca_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiryvote',
            index=models.Index(fields=['inquiry', 'choice'], name='inquiries_i_inquiry_0fe067_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inquiryvote',
            unique_together={('inquiry', 'user')},
        ),
    ]
