# Generated by Django 5.2.6 on 2026-09-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_global_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Masalan: Axborot texnologiyalari boshqarmasi', max_length=150, unique=True, verbose_name="Boshqarma / Bo'lim nomi")),
                ('code', models.CharField(blank=True, help_text='Masalan: IT, HR, PMO, FIN', max_length=50, verbose_name='Boshqarma kodi / Qisqartmasi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif / Vazifalari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Boshqarma',
                'verbose_name_plural': 'Boshqarmalar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='global_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOSS', 'Boshliq'), ('MANAGER', 'Loyiha menejeri'), ('OPERATOR', 'Operator'), ('DEVELOPER', 'Dasturchi')], default='DEVELOPER', max_length=20, verbose_name='Tizim roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text="Masalan: Bosh mutaxassis, Bo'lim boshlig'i, Dasturchi", max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Foydalanuvchi biriktirilgan boshqarma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department', verbose_name='Boshqarma'),
        ),
    ]
