# Generated by Django 5.2.6 on 2026-09-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_alter_user_global_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_inquiries',
            field=models.BooleanField(default=False, help_text="Ushbu foydalanuvchiga So'rovlar bo'limiga kirish ruxsatini berish", verbose_name="So'rovlar bo'limiga kirish"),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Foydalanuvchi faoliyat yuritadigan boshqarma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department', verbose_name='Boshqarma nomi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Tizimga kirish uchun login sifatida ishlatiladi', max_length=254, unique=True, verbose_name='Login (Email)'),
        ),
    ]
