# Generated by Django 5.2.6 on 2026-09-08 06:32

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_can_access_inquiries_alter_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyAnalytics',
            fields=[
            ],
            options={
                'verbose_name': 'Mutaxassisliklar tahlili',
                'verbose_name_plural': 'Mutaxassisliklar tahlili',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='global_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOSS', 'Boshliq'), ('MANAGER', 'Loyiha menejeri'), ('OPERATOR', 'Operator'), ('DEVELOPER', 'Dasturchi'), ('SOHAVIY', 'Sohaviy boshqarmalar')], default='DEVELOPER', max_length=20, verbose_name='Tizim roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('BACKEND', 'Backend dasturchi'), ('FRONTEND', 'Frontend dasturchi'), ('FULLSTACK', 'Fullstack dasturchi'), ('MOBILE', 'Mobil dasturchi'), ('DEVOPS', 'DevOps muhandisi'), ('QA', 'Tester (QA)'), ('DESIGNER', 'UI/UX dizayner'), ('DATA', 'Data / ML muhandisi'), ('ANALYST', 'Biznes tahlilchi'), ('SECURITY', 'Xavfsizlik mutaxassisi'), ('PM', 'Loyiha menejeri'), ('SOHAVIY', 'Sohaviy boshqarmalar')], default='BACKEND', help_text='Royxatdan otishda tanlanadi va vazifa taqsimotiga tasir qiladi', max_length=20, verbose_name='Mutaxassislik'),
        ),
    ]
