# Generated by Django 5.2.6 on 2026-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_specialtyanalytics_alter_user_global_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='global_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BOSS', 'Boshliq'), ('MANAGER', 'Loyiha menejeri'), ('OPERATOR', 'Operator'), ('DEVELOPER', 'Dasturchi'), ('SOHAVIY', 'Boshqarma')], default='DEVELOPER', max_length=20, verbose_name='Tizim roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('BACKEND', 'Backend dasturchi'), ('FRONTEND', 'Frontend dasturchi'), ('FULLSTACK', 'Fullstack dasturchi'), ('MOBILE', 'Mobil dasturchi'), ('DEVOPS', 'DevOps muhandisi'), ('QA', 'Tester (QA)'), ('DESIGNER', 'UI/UX dizayner'), ('DATA', 'Data / ML muhandisi'), ('ANALYST', 'Biznes tahlilchi'), ('SECURITY', 'Xavfsizlik mutaxassisi'), ('PM', 'Loyiha menejeri'), ('SOHAVIY', 'Boshqarma')], default='BACKEND', help_text='Royxatdan otishda tanlanadi va vazifa taqsimotiga tasir qiladi', max_length=20, verbose_name='Mutaxassislik'),
        ),
    ]
