# Generated by Django 5.2.6 on 2026-09-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_global_role_alter_user_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Masalan: DEVOPS, AI, SYSADMIN (Lotin harflarida)', max_length=50, unique=True, verbose_name='Kod / Identifikator')),
                ('name', models.CharField(help_text="Masalan: DevOps muhandisi, Sun'iy intellekt mutaxassisi", max_length=100, verbose_name='Mutaxassislik nomi')),
                ('icon', models.CharField(blank=True, default='*', max_length=30, verbose_name='Belgi / Icon')),
                ('color', models.CharField(blank=True, default='#2563eb', max_length=30, verbose_name='Rang (HEX)')),
                ('skills', models.CharField(blank=True, help_text='Vergul bilan: Docker, Kubernetes, Linux', max_length=255, verbose_name="Asosiy ko'nikmalar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('BACKEND', 'Backend dasturchi'), ('FRONTEND', 'Frontend dasturchi'), ('FULLSTACK', 'Fullstack dasturchi'), ('MOBILE', 'Mobil dasturchi'), ('DEVOPS', 'DevOps muhandisi'), ('QA', 'Tester (QA)'), ('DESIGNER', 'UI/UX dizayner'), ('DATA', 'Data / ML muhandisi'), ('ANALYST', 'Biznes tahlilchi'), ('SECURITY', 'Xavfsizlik mutaxassisi'), ('PM', 'Loyiha menejeri'), ('SOHAVIY', 'Sohaviy boshqarmalar')], default='BACKEND', help_text='Royxatdan otishda tanlanadi va vazifa taqsimotiga tasir qiladi', max_length=20, verbose_name='Mutaxassislik'),
        ),
    ]
