# Generated by Django 5.2.6 on 2026-09-10 10:47

from django.db import migrations, models


def migrate_specialties_data(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    SpecialtyItem = apps.get_model('accounts', 'SpecialtyItem')

    # 1. Mavjud foydalanuvchilarning mutaxassisliklarini moslashtirish
    dev_specs = ['BACKEND', 'FRONTEND', 'FULLSTACK', 'MOBILE', 'DEVOPS', 'QA', 'DESIGNER', 'DATA', 'SECURITY']
    User.objects.filter(specialty__in=dev_specs).update(specialty='DEVELOPER')
    User.objects.filter(specialty='ANALYST').update(specialty='OTHER')
    # Boshqa noma'lum qiymatlar bo'lsa DEVELOPER ga o'tkazish
    User.objects.exclude(specialty__in=['DEVELOPER', 'SOHAVIY', 'PM', 'OTHER']).update(specialty='DEVELOPER')

    # 2. SpecialtyItem jadvalini 4 ta mutaxassislikka yangilash
    SpecialtyItem.objects.all().delete()
    items = [
        {
            "code": "DEVELOPER",
            "name": "Dasturchi",
            "icon": "</>",
            "color": "#2f81f7",
            "skills": "Backend, Frontend, Fullstack, Mobile, DevOps, QA, Database",
            "is_active": True,
            "order": 1,
        },
        {
            "code": "SOHAVIY",
            "name": "Boshqarmalar",
            "icon": "[S]",
            "color": "#0284c7",
            "skills": "Buyurtmalar, Talablar tahlili, Boshqarma nazorati, Texnik talabnoma",
            "is_active": True,
            "order": 2,
        },
        {
            "code": "PM",
            "name": "Loyiha menejeri",
            "icon": "= >",
            "color": "#8b949e",
            "skills": "Rejalashtirish, Agile, Risk boshqaruvi, Kommunikatsiya",
            "is_active": True,
            "order": 3,
        },
        {
            "code": "OTHER",
            "name": "Boshqa",
            "icon": "*",
            "color": "#a371f7",
            "skills": "Umumiy ko'nikmalar, Hujjatlar, Tahlil",
            "is_active": True,
            "order": 4,
        },
    ]
    for item_data in items:
        SpecialtyItem.objects.create(**item_data)


def rollback_specialties_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_specialtyitem_alter_user_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(choices=[('DEVELOPER', 'Dasturchi'), ('SOHAVIY', 'Boshqarmalar'), ('PM', 'Loyiha menejeri'), ('OTHER', 'Boshqa')], default='DEVELOPER', help_text='Royxatdan otishda tanlanadi va vazifa taqsimotiga tasir qiladi', max_length=20, verbose_name='Mutaxassislik'),
        ),
        migrations.RunPython(migrate_specialties_data, rollback_specialties_data),
    ]
