# Generated by Django 5.2.6 on 2026-09-07 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectmember_projects_pr_user_id_5f83f5_idx'),
        ('tasks', '0006_task_tasks_task_due_dat_bce847_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'deleted_at', 'status'], name='tasks_task_project_bdde34_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deleted_at', 'due_date'], name='tasks_task_deleted_8ec6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['user', 'is_active'], name='tasks_taska_user_id_4e0b00_idx'),
        ),
    ]
