# Generated by Django 5.2.6 on 2026-09-11 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_changerequest_department_and_more'),
        ('tasks', '0007_task_tasks_task_project_bdde34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.ForeignKey(blank=True, help_text="Ushbu vazifa bog'langan buyurtma", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='orders.changerequest', verbose_name='Tegishli buyurtma (TZ)'),
        ),
    ]
