# Generated by Django 5.2.6 on 2026-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='allocated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Rejalashtirilgan soat'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muddat'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='note',
            field=models.CharField(blank=True, max_length=250, verbose_name='Eslatma / Vazifa mazmuni'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='role',
            field=models.CharField(blank=True, max_length=120, verbose_name='Jamoada roli'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish sanasi'),
        ),
    ]
