# Generated by Django 5.2.6 on 2026-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitexts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='branding', max_length=60, unique=True, verbose_name='Sozlama kaliti')),
                ('app_name', models.CharField(default='TeamFlow', max_length=150, verbose_name='Tizim / Loyiha nomi')),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/', verbose_name='Logotip')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
    ]
