# Generated by Django 5.2.6 on 2026-09-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitexts', '0002_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': 'Brending va logotip sozlamasi', 'verbose_name_plural': 'Brending va logotip sozlamalari'},
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='app_name',
            field=models.CharField(default='TeamFlow', help_text="Masalan: 'TeamFlow', 'Mening Kompaniyam' yoki loyihangiz nomi. Ushbu nom butun tizim bo'ylab (Admin panel, foydalanuvchilar paneli, xabarnomalar va brauzer sarlavhasi) darhol o'zgaradi.", max_length=150, verbose_name='Tizim / Loyiha nomi'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='logo',
            field=models.FileField(blank=True, help_text="Tizim logotipi uchun rasm faylini tanlang (PNG, SVG, JPG, WebP). Saqlash tugmasini bosishingiz bilan butun saytda yangi logotip ko'rinadi.", null=True, upload_to='branding/', verbose_name='Yangi logotip yuklash'),
        ),
    ]
