# Generated by Django 5.2.6 on 2026-09-23 09:11

import apps.uitexts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitexts', '0003_alter_systemsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='logo',
            field=models.FileField(blank=True, help_text="Tizim logotipi uchun rasm faylini tanlang (PNG, SVG, JPG, WebP). Saqlash tugmasini bosishingiz bilan butun saytda yangi logotip ko'rinadi.", null=True, upload_to=apps.uitexts.models.branding_logo_upload_to, verbose_name='Yangi logotip yuklash'),
        ),
    ]
